(() => {
  'use strict';
  const KEYS = ['date','time','weight','bodyFat','muscleMass','bmi','visceralFat','basalMetabolism','bodyAge','boneMass','muscleQuality','bodyWater','pulse'];
  const LABELS = {date:'測定日',time:'測定時刻',weight:'体重',bodyFat:'体脂肪率',muscleMass:'筋肉量',bmi:'BMI',visceralFat:'内臓脂肪レベル',basalMetabolism:'基礎代謝量',bodyAge:'体内年齢',boneMass:'推定骨量',muscleQuality:'筋質点数',bodyWater:'体水分率',pulse:'脈拍'};
  const UNITS = {weight:'kg',bodyFat:'%',muscleMass:'kg',bmi:'',visceralFat:'',basalMetabolism:'kcal',bodyAge:'歳',boneMass:'kg',muscleQuality:'点',bodyWater:'%',pulse:'拍/分'};
  const RANGES = {weight:[20,250],bodyFat:[2,70],muscleMass:[10,150],bmi:[10,60],visceralFat:[1,60],basalMetabolism:[500,4000],bodyAge:[10,100],boneMass:[.5,10],muscleQuality:[0,100],bodyWater:[20,80],pulse:[30,220]};
  const ROI_KEY='my-body-log-healthplanet-roi-v2', MAX_IMAGE_BYTES=25*1024*1024, MAX_IMAGE_PIXELS=36_000_000;
  const $=s=>document.querySelector(s), fileInput=$('#healthPlanetImage'), status=$('#healthPlanetOcrStatus'), resultBox=$('#healthPlanetOcrResults'), calibration=$('#healthPlanetCalibration'), canvas=$('#healthPlanetCalibrationCanvas'), ctx=canvas.getContext('2d',{willReadFrequently:true});
  let regions=readRegions(), pendingImage=null, pendingUrl=null, dragStart=null, dragCurrent=null, calibrationForAdjustment=false;
  function readRegions(){try{const v=JSON.parse(localStorage.getItem(ROI_KEY)||'null')||window.MY_BODY_LOG_HP_ROIS;return v&&KEYS.every(k=>validRegion(v[k]))?v:null}catch{return null}}
  function validRegion(r){return r&&[r.x,r.y,r.w,r.h].every(Number.isFinite)&&r.x>=0&&r.y>=0&&r.w>0&&r.h>0&&r.x+r.w<=1&&r.y+r.h<=1}
  function setStatus(s,type=''){status.textContent=s;status.className=`ocr-status ${type}`.trim()}
  function cleanupImage(){if(pendingUrl)URL.revokeObjectURL(pendingUrl);pendingUrl=null;pendingImage=null;dragStart=dragCurrent=null;fileInput.value='';ctx.clearRect(0,0,canvas.width,canvas.height);calibration.classList.add('hidden')}
  function loadImage(file){return new Promise((resolve,reject)=>{const img=new Image();pendingUrl=URL.createObjectURL(file);img.onload=()=>img.naturalWidth*img.naturalHeight>MAX_IMAGE_PIXELS?reject(Error('画像の解像度が大きすぎます。')):resolve(img);img.onerror=()=>reject(Error('画像を開けません。HealthPlanetのスクリーンショットを選び直してください。'));img.src=pendingUrl})}
  function drawRegions(){if(!pendingImage)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(pendingImage,0,0,canvas.width,canvas.height);if(regions)KEYS.forEach(k=>{const r=regions[k];if(!r)return;ctx.strokeStyle=k===$('#healthPlanetTarget').value?'#f28c28':'#218b62';ctx.lineWidth=Math.max(2,canvas.width/420);ctx.strokeRect(r.x*canvas.width,r.y*canvas.height,r.w*canvas.width,r.h*canvas.height)});if(dragStart&&dragCurrent){ctx.strokeStyle='#f28c28';ctx.lineWidth=3;ctx.strokeRect(dragStart.x,dragStart.y,dragCurrent.x-dragStart.x,dragCurrent.y-dragStart.y)}}
  function showCalibration(img,adjust=false){pendingImage=img;calibration.classList.remove('hidden');resultBox.classList.add('hidden');const scale=Math.min(1,1800/img.naturalWidth,2400/img.naturalHeight);canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);drawRegions();const count=KEYS.filter(k=>validRegion(regions?.[k])).length;$('#healthPlanetCalibrationHint').textContent=adjust?'画像内の枠が数字からずれている場合、項目を選んで値を囲み直してください。':'画像の数値領域を選択して囲んでください。';$('#saveHealthPlanetRegions').disabled=count!==KEYS.length;$('#runHealthPlanetOcr').classList.toggle('hidden',count!==KEYS.length);$('#healthPlanetCalibrationHint').dataset.count=`${count}/${KEYS.length}`;setStatus(adjust?'読み取り領域を確認・調整できます。':'初回設定です。領域を保存すると次回から自動で読み取ります。')}
  function point(e){const b=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-b.left)*canvas.width/b.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-b.top)*canvas.height/b.height))}}
  canvas.addEventListener('pointerdown',e=>{if(!pendingImage)return;canvas.setPointerCapture(e.pointerId);dragStart=dragCurrent=point(e);drawRegions()});canvas.addEventListener('pointermove',e=>{if(dragStart){dragCurrent=point(e);drawRegions()}});canvas.addEventListener('pointerup',e=>{if(!dragStart)return;dragCurrent=point(e);const x=Math.min(dragStart.x,dragCurrent.x),y=Math.min(dragStart.y,dragCurrent.y),w=Math.abs(dragCurrent.x-dragStart.x),h=Math.abs(dragCurrent.y-dragStart.y);dragStart=dragCurrent=null;if(w<12||h<8){drawRegions();return}regions||={};regions[$('#healthPlanetTarget').value]={x:x/canvas.width,y:y/canvas.height,w:w/canvas.width,h:h/canvas.height};drawRegions();const n=KEYS.filter(k=>validRegion(regions[k])).length;$('#healthPlanetCalibrationHint').textContent=`${LABELS[$('#healthPlanetTarget').value]}を設定しました（${n}/${KEYS.length}）。`;$('#saveHealthPlanetRegions').disabled=n!==KEYS.length;$('#runHealthPlanetOcr').classList.toggle('hidden',n!==KEYS.length)});
  $('#healthPlanetTarget').addEventListener('change',drawRegions);
  $('#saveHealthPlanetRegions').addEventListener('click',()=>{if(!KEYS.every(k=>validRegion(regions?.[k])))return;try{localStorage.setItem(ROI_KEY,JSON.stringify(regions))}catch{};$('#runHealthPlanetOcr').classList.remove('hidden');processImage(pendingImage)});
  $('#runHealthPlanetOcr').addEventListener('click',()=>processImage(pendingImage));$('#chooseHealthPlanetImage').addEventListener('click',()=>fileInput.click());$('#adjustHealthPlanetRegions').addEventListener('click',()=>{calibrationForAdjustment=true;fileInput.click()});
  fileInput.addEventListener('change',async()=>{const file=fileInput.files?.[0];if(!file)return;const adjust=calibrationForAdjustment;calibrationForAdjustment=false;cleanupImage();resultBox.classList.add('hidden');if(!file.type.startsWith('image/')||file.size>MAX_IMAGE_BYTES){setStatus(file.size>MAX_IMAGE_BYTES?'画像サイズが25MBを超えています。':'画像ファイルを選んでください。','error');return}try{setStatus('画像を開いています…');const img=await loadImage(file);if(adjust||!regions||Math.abs(img.naturalWidth/img.naturalHeight-870/1882)>.035)showCalibration(img,adjust);else processImage(img)}catch(e){setStatus(e.message||'画像を読み込めませんでした。','error');cleanupImage()}});
  function preprocess(src){const out=document.createElement('canvas'),scale=Math.max(2,Math.min(4,Math.ceil(900/src.width)));out.width=Math.max(1,Math.round(src.width*scale));out.height=Math.max(1,Math.round(src.height*scale));const c=out.getContext('2d',{willReadFrequently:true});c.imageSmoothingEnabled=false;c.drawImage(src,0,0,out.width,out.height);const p=c.getImageData(0,0,out.width,out.height);for(let i=0;i<p.data.length;i+=4){const g=.299*p.data[i]+.587*p.data[i+1]+.114*p.data[i+2],v=(g-128)*1.45+128,b=v>174?255:0;p.data[i]=p.data[i+1]=p.data[i+2]=b}c.putImageData(p,0,0);return out}
  function clean(s){return String(s||'').replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xFEE0)).replace(/[．。]/g,'.').replace(/[：]/g,':').replace(/[／]/g,'/')}
  function parse(key,text){const s=clean(text);if(key==='date'){const m=s.match(/(\d{1,4})\s*[/.年-]\s*(\d{1,2})\s*[/.月-]?\s*(\d{1,2})?/);if(!m)return null;const now=new Date(),year=m[3]?Number(m[1]):now.getFullYear(),month=m[3]?Number(m[2]):Number(m[1]),day=m[3]?Number(m[3]):Number(m[2]);if(month<1||month>12||day<1||day>31)return null;return `${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`}if(key==='time'){const m=s.match(/(\d{1,2})\s*:\s*(\d{2})/);if(!m||Number(m[1])>23||Number(m[2])>59)return null;return `${m[1].padStart(2,'0')}:${m[2]}`}const m=s.replace(/\s/g,'').match(/\d+(?:\.\d+)?/);return m?Number(m[0]):null}
  function previous(k){return records.find(r=>r.id!==currentId&&r[k]!=null)}
  function assess(k,v,confidence){if(k==='date'||k==='time')return {review:v==null,note:v==null?'読み取れませんでした。フォームで入力してください。':`認識信頼度 ${Math.round(confidence)}%`};const [min,max]=RANGES[k];if(v<min||v>max)return{review:true,note:`範囲外（${min}〜${max}${UNITS[k]}）。フォームには入れていません。`};const p=previous(k),threshold={weight:5,bodyFat:8,muscleMass:4,bmi:6,visceralFat:8,basalMetabolism:500,bodyAge:15,boneMass:2,muscleQuality:30,bodyWater:15,pulse:50}[k];if(p&&Math.abs(v-p[k])>threshold){const d=v-p[k];return{review:true,note:`前回から ${d>0?'+':''}${d.toFixed(2)}${k==='bodyFat'||k==='bodyWater'?'pt':UNITS[k]}です。確認してください。`}}if(confidence<70)return{review:true,note:`認識信頼度 ${Math.round(confidence)}%。値を確認してください。`};if(confidence<86)return{review:true,note:`認識信頼度 ${Math.round(confidence)}%。念のため確認してください。`};return{review:false,note:`認識信頼度 ${Math.round(confidence)}%`}}
  function cropFor(img,r){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*r.w));c.height=Math.max(1,Math.round(img.naturalHeight*r.h));c.getContext('2d').drawImage(img,Math.round(img.naturalWidth*r.x),Math.round(img.naturalHeight*r.y),c.width,c.height,0,0,c.width,c.height);return c}
  async function processImage(img){if(!regions||!KEYS.every(k=>validRegion(regions[k]))){showCalibration(img);return}calibration.classList.add('hidden');resultBox.classList.remove('hidden');resultBox.innerHTML='';const collected=[];let worker;try{const base=p=>new URL(p,document.baseURI).href;setStatus('画像を読み取っています… OCRエンジンを準備中');worker=await Tesseract.createWorker('eng',1,{workerPath:base('./vendor/tesseract/worker.min.js'),langPath:base('./vendor/tesseract/lang'),corePath:base('./vendor/tesseract/core/tesseract-core.wasm.js'),gzip:true,cacheMethod:'write',logger:m=>{if(m.status)setStatus(`画像を読み取っています… ${m.status}${Number.isFinite(m.progress)?` ${Math.round(m.progress*100)}%`:''}`)}});for(let i=0;i<KEYS.length;i++){const k=KEYS[i];setStatus(`画像を読み取っています… ${LABELS[k]}（${i+1}/${KEYS.length}）`);let result;try{await worker.setParameters({tessedit_char_whitelist:k==='date'?'0123456789/.-年月日':k==='time'?'0123456789:':'0123456789.'});const {data}=await worker.recognize(preprocess(cropFor(img,regions[k])));const v=parse(k,data.text),confidence=Number(data.confidence)||0,check=assess(k,v,confidence);result={key:k,value:v,confidence,...check};if(v!=null&&!check.note.startsWith('範囲外')){if(k==='date'||k==='time')$('#entryForm').elements[k].value=v;else $('#entryForm').elements[k].value=v}}catch{result={key:k,value:null,confidence:0,review:true,note:'読み取りに失敗しました。手入力してください。'}}collected.push(result);renderResults(collected)}if(collected.some(r=>r.value!=null&&!r.note.startsWith('範囲外')))entrySource='healthplanet-image';if(collected.some(r=>['visceralFat','basalMetabolism','bodyAge','boneMass','muscleQuality','bodyWater','pulse'].includes(r.key)&&r.value!=null))$('#otherFields').closest('details').open=true;setStatus('読み取り完了。各項目と入力欄を確認してから保存してください。',collected.some(r=>r.review)?'warning':'');$('#adjustHealthPlanetRegions').classList.remove('hidden')}catch(e){setStatus(`OCRを開始できませんでした: ${e?.message||'初期化エラー'}。入力欄へ手入力できます。`,'error')}finally{if(worker)await worker.terminate().catch(()=>{});cleanupImage()}}
  function renderResults(rs){resultBox.innerHTML=rs.map(r=>{const v=r.value==null?'—':typeof r.value==='number'?`${r.value.toFixed(2)} ${UNITS[r.key]||''}`.trim():r.value;return `<div class="ocr-result-row ${r.value==null?'unread':r.review?'needs-review':''}"><span>${LABELS[r.key]}</span><span><strong>${v}</strong><span class="ocr-result-note">${r.note}</span></span></div>`}).join('')+KEYS.slice(rs.length).map(k=>`<div class="ocr-result-row unread"><span>${LABELS[k]}</span><span><strong>—</strong><span class="ocr-result-note">読み取り中</span></span></div>`).join('')}
  window.healthPlanetOcr={resetForEntry(){cleanupImage();resultBox.classList.add('hidden');resultBox.innerHTML='';setStatus('');calibrationForAdjustment=false;$('#adjustHealthPlanetRegions').classList.toggle('hidden',!regions)}};
})();
